name: Render

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          TZ: 'Asia/Tokyo'
        run:
          echo $(date +'%Y-%m-%d %H:%M:%S')
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run:
          python3 -m pip install pip setuptools --upgrade
          python3 -m pip install -r requirements.txt
          python3 -m render
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist